# must accept EULA the first time that the image is started
# docker run splunk/universalforwarder:6.5.2
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/universalforwarder:6.5.2
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunkuniversalforwarder:6.5.2 
version: '2'
services:
  vsplunk_uf:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
  splunkuniversalforwarder:
#    build: .
    hostname: splunkuniversalforwarder
    image: splunk/universalforwarder:6.5.2
#    environment:
#      SPLUNK_START_ARGS: --accept-license
    volumes_from:
      - vsplunk_uf
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"