# must accept EULA the first time that the image is started

# docker run splunk/universalforwarder:7.0.3
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/universalforwarder:7.0.3
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunkuniversalforwarder:7.0.3 

# Support for Docker Compose v3, https://docs.docker.com/compose/overview/
version: '3'

volumes:
  opt-splunk-etc:
  opt-splunk-var:

services:
  splunkuniversalforwarder:
#    build: .
    hostname: splunkuniversalforwarder
    image: splunk/universalforwarder:7.0.3
#    environment:
#      SPLUNK_START_ARGS: --accept-license
    volumes:
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"

